com/two/dyb作业/day1111(1)/ajaxpro/ajaxpro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lrapp/',include('l_rapp.urls')),
]

com/two/dyb作业/day1111(1)/ajaxpro/l_rapp/urls.py
from django.urls import path

from l_rapp import views

app_name = 'l_rapp'
urlpatterns = [
    path('register/',views.register,name='register'),
    path('registerlogic/',views.register_logic,name='registerlogic'),
    path('login/',views.login,name='login'),
    path('loginlogic/',views.login_logic,name='loginlogic'),
    path('checkname/',views.check_name,name='checkname'),
    path('query/',views.query,name='query'),
    path('querylogic/',views.query_logic,name='querylogic'),
    path('demo1/',views.demo1,name='demo1'),
    path('demo2/',views.demo2,name='demo2'),
    path('demo3/',views.demo3,name='demo3'),
]

com/two/dyb作业/day1111(1)/ajaxpro/l_rapp/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    name = models.CharField(max_length=20)
    pwd = models.CharField(max_length=20)


'''
1.创建 model
2、生成迁移记录并应用到数据库
3.mysql数据库去做查询 表  
    - sqlite3 数据表 sqlite export 
'''

com/two/dyb作业/day1111(1)/ajaxpro/l_rapp/views.py
import time

from django.db import transaction
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse

from l_rapp.models import User
# Create your views here.
import json

# 创建视图函数
# login
# register
def register(request):
    # rst = request.GET.get('msg')
    # print(rst)  # 验证是否能接受到
    return render(request,'l_rapp/register.html')

# 注册到数据库表中
def register_logic(request):
    name = request.POST.get('username')
    pwd = request.POST.get('userpwd')
    # 添加到数据表中  该用户名已存在？？
    try:
        with transaction.atomic():
            User.objects.create(name=name,pwd=pwd)
            return HttpResponse('注册成功')
    except:
        return HttpResponse('注册失败')




def login(request):


    return render(request,'l_rapp/login.html')


def login_logic(request):
    name = request.POST.get('username')
    pwd = request.POST.get('userpwd')

    rst = User.objects.filter(name=name,pwd=pwd)
    print(rst)
    return HttpResponse('登录成功')



# 验证 用户名 视图函数
def check_name(request):
    # print('验证用户名')
    name = request.GET.get('name')
    print(name)
    # time.sleep(100)
    # 连接数据库 进行验证
    if name == 'sunge':
        return HttpResponse('用户名已存在')
    else:
        return HttpResponse('用户名可用')


# query 模板文件 调度
def query(request):
    return render(request,'l_rapp/query.html')


def mydefault(u):
    print(u)
    if isinstance(u, User):
        return {'id': u.id, 'name': u.name, 'pwd': u.pwd}

# 调度 model 完成 数据获取工作
def query_logic(request):
    # 接收请求，返回响应 表中数据
    # 第一种：直接 返回响应 httpresponse() model对象 queryset对象 不可行
    # rst = User.objects.all()
    # print(rst)
    # return HttpResponse(rst[0])

    # 第二种 换格式  非官方
    # rst = User.objects.all()
    # s1 = ''
    # for user in rst:
    #     s1 += str(user.id) + ','
    #     s1 += user.name + ','
    #     s1 += user.pwd + ','
    # return HttpResponse(s1)

    # 第三种： render() 不推荐 大量冗余代码
    # rst = User.objects.all()
    # return render(request,'l_rapp/index.html',{'users':rst})

    # 第四种：xml 数据传输格式 <users><user><name>user.name<name><pwd>user.pwd<pwd><user></users>
    # < users > < user > < name > user.name < name > < pwd > user.pwd < pwd > < user > < / users >
    # return HttpResponse(rst)
    # 原生app开发  html css js 解析
    # 当前 最新数据传输格式  xml 很传统处理方式
    # json

    # 第五种：json 数据传输格式
    # dict1 = {'name': 'liuzong', 'age': 18}
    # rst = json.dumps(dict1)
    # print(rst)
    # users = User.objects.all()
    # rst = json.dumps(list(users), default=mydefault)
    # print(rst, type(rst))
    # return HttpResponse(rst)



    # jsonresponse对象
    users = User.objects.all()
    return JsonResponse({'users':list(users)},json_dumps_params={'default':mydefault})


'''
对比：
    Jsonresponse() 直接返回响应 无需使用HTTPRESPONSE()
    Jsonresponse() 同时具备json序列化 工作
    Jsonresponse() 传输 json对象
    
'''

# 分别对应 视图demo
def demo1(request):
    return render(request,'l_rapp/demo1.html')

def demo2(request):
    return render(request,'l_rapp/demo2.html')

def demo3(request):
    return render(request,'l_rapp/demo3.html')

com/two/dyb作业/day1111(1)/ajaxpro/templates/l_rapp/demo1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div>我是demo1页面</div>
</body>
</html>

com/two/dyb作业/day1111(1)/ajaxpro/templates/l_rapp/demo2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div>我是demo2页面</div>
</body>
</html>

com/two/dyb作业/day1111(1)/ajaxpro/templates/l_rapp/demo3.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div>我是demo3页面</div>
</body>
</html>

com/two/dyb作业/day1111(1)/ajaxpro/templates/l_rapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{#接收后端 数据#}
{#{{ users }}#}
<table border="1" cellspacing="0">
    <tr>
        <td>编号</td>
        <td>姓名</td>
        <td>密码</td>
    </tr>
    {% for user in users %}
        <tr>
            <td>{{ user.id }}</td>
            <td>{{ user.name }}</td>
            <td>{{ user.pwd }}</td>
        </tr>
    {% endfor %}

</table>
</body>
</html>

com/two/dyb作业/day1111(1)/ajaxpro/templates/l_rapp/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录页面</title>
</head>
<body>
<form action="{% url 'l_rapp:loginlogic' %}" method="post">
    {% csrf_token %}
    用户名：<input type="text" name="username"><br>
    密码：<input type="password" name="userpwd"><br>
    <input type="submit" value="登录">
</form>
</body>
</html>

com/two/dyb作业/day1111(1)/ajaxpro/templates/l_rapp/query.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>数据查询显示</title>
</head>
<body>
{% load static %}
<h1>进行数据查询显示</h1>
<input type="button" value="查询" onclick="fn()">
<div id="div01" style="background-color:red;height: 100px;"></div>
<div id="div02" style="background-color:pink;height: 100px;"></div>
<div id="div03" style="background-color:yellow;height: 100px;"></div>

<table border="1"></table>
<script src="{% static 'jquery-1.11.1.js' %}"></script>
<script>

    //fn发送 ajax请求
    {#$('div').load("{% url 'l_rapp:querylogic' %}");#}
    $('#div01').load("{% url 'l_rapp:demo1' %}");
    $('#div02').load("{% url 'l_rapp:demo2' %}");
    $('#div03').load("{% url 'l_rapp:demo3' %}");
    //fn 发送post请求 post()
    function fn1(){
        $.post(
            "{% url 'l_rapp:querylogic' %}",
            'name=liuzong&age=28&csrfmiddlewaretoken={{ csrf_token }}',
            function(msg) {
                console.log('post');
                console.log(msg);//接收到 js对象
            },
            'text'
        );
    }

    //fn 发送 get请求 get()
    function fn1(){
        $.get(
            "{% url 'l_rapp:querylogic' %}",
            'name=liuzong&age=28',
            function(msg) {
                console.log('get');
                console.log(msg);//接收到 js对象
            },
            'text'
        );
    }


    //fn 发送 post请求 jq版
     function fn1() {
        //配置参数工作
         $.ajaxSetup({
              url : "{% url 'l_rapp:querylogic' %}",
             headers:{"X-CSRFToken":"{{ csrf_token }}"}
         });
        $.ajax({
            type: 'post',

            data: 'name=liuzong&age=28',
            success: function(msg) {
                console.log('ajax+ajaxsetup');
                console.log(msg);//接收到 js对象
            }

    });

}

    //fn 发送ajax请求 jq版 get请求
    function fn1() {
        //
        $.ajax({
            type: 'get',
            url : "{% url 'l_rapp:querylogic' %}",
            data: 'name=liuzong&age=28',
            success: function(msg) {
                console.log(msg);//接收到 js对象
            }

    });






    }



    function fn1() {
        //发送 ajax请求
    var xhr;
    if (window.XMLHttpRequest) {
        xhr = new XMLHttpRequest();
    } else if (window.ActiveXObject) {
        xhr = new ActiveXObject('Microsoft.XMLHTTP');
    }
    //初始化 配置
    // url  查询所有的数据表 数据
    xhr.open('get',"{% url 'l_rapp:querylogic' %}",true);
    xhr.send();

    //接收响应
    xhr.onreadystatechange = function () {
        if (xhr.readyState === 4 && xhr.status === 200) {
            var rst = xhr.responseText; //数组
            console.log(rst);//字符串
            console.log(JSON.parse(rst)); //js识别 原生对象
            {#console.log(typeof(rst),rst);  //string 字符串#}
            {#document.getElementsByTagName('div')[0].innerHTML = rst;#}


            //创建表格
            //
            {#var info = '';#}
            {#for (var i = 0; i < rst.length; i++) {#}
            {#    info += '<tr>';#}
            {#    info += '<td>' + rst[i].id + '</td>';#}
            {#    info += '<td>' + rst[i].name + '</td>';#}
            {#    info += '<td>' + rst[i].pwd + '</td>';#}
            {#    info += '</tr>';#}

            {#document.getElementsByTagName('table')[0].innerHTML = info;#}


            //创建表格
            {#for (var i = 0; i < rst.length; i++) {#}
            {#    //#}
            {#    var tr = document.createElement('tr');#}
            {#    //js 对象可以遍历#}
            {#    for (var k in rst[i]) {#}
            {#        var td = document.createElement('td');#}
            {#        td.innerHTML = rst[i][k];#}
            {#        tr.appendChild(td);#}
            {#    }#}
            {#    document.getElementsByTagName('table')[0].appendChild(tr);#}

        }
    }










    }






</script>
</body>
</html>

com/two/dyb作业/day1111(1)/ajaxpro/templates/l_rapp/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册页面</title>
</head>
<body>
<form action="{% url 'l_rapp:registerlogic' %}" method="post">
    {% csrf_token %}
    用户名：<input type="text" name="username" onblur="fn();"><span></span><br>
    密码：<input type="password" name="userpwd"><br>
    <input type="submit" value="注册">
</form>
<script>

    //发送 post请求
    function fn() {
        //
        var username = document.getElementsByName('username')[0];
        //ajax请求
        if (window.XMLHttpRequest) {
            var xhr = new XMLHttpRequest();
        } else if (window.ActiveXObject) {
            var xhr = new ActiveXObject('Microsoft.XMLHTTP');
        }
        //2.发送请求之前 配置 初始化工作
        // post请求方式 发送参数 不拼接在url之后，单独发送send()
        var url = '{% url "l_rapp:checkname" %}';
        xhr.open('post',url,true);

        //设置请求头 设置 csrf防御机制
        xhr.setRequestHeader("X-CSRFToken", '{{ csrf_token }}');
        xhr.setRequestHeader('Content-type','application/x-www-form-urlencoded');
        //3.发送请求
        //send() 参数 携带数据  多个数据之间 &分隔
        xhr.send('name='+username.value + '&age=18');
        //4. 接收响应结果
        xhr.onreadystatechange = function () {
            if (xhr.readyState === 4 && xhr.status === 200) {
                //
                console.log(xhr.responseText);
            }
        }








    }











    //发送请求 验证用户名是否存在？
    //发送 get请求
    function fn1() {
        var username = document.getElementsByName('username')[0];
        //发送请求给后端 连接数据库验证
        {#window.location.href = '{% url "l_rapp:checkname" %}';#}
{#        使用ajax技术#}
        //1.创建 对象 xhr ajax 对象 标准浏览器 不识别ie5 /6
        var xhr;
        if (window.XMLHttpRequest) {
            xhr = new XMLHttpRequest();
        } else if (window.ActiveXObject) {
            xhr = new ActiveXObject('Microsoft.XMLHTTP');
        }
        //2.配置 参数
        // 三个参数：请求方式 get/post 请求url  是否异步
        //url 请求路径 后端  传参
        // get请求方式 传参 拼接在url之后  username.value 用户名值
        var url = '{% url "l_rapp:checkname" %}?name=' + username.value;
        xhr.open('get',url,true);
        //3.发送请求
        xhr.send();
        //4.接收响应结果
        {#console.log(xhr.responseText);#}
        // 回调函数
        xhr.onreadystatechange = function() {
            console.log(xhr.readyState);
            if (xhr.readyState === 4 && xhr.status === 200) {
            //接收结果
                console.log(xhr.responseText);
                {#if xhr.responseText === '1':#}
                {#    document.getElementsByTagName('span')[0].innerHTML = '<img src="红叉">';#}
                {#else if xhr.responseText === '0':#}
                {#    document.getElementsByTagName('span')[0].innerHTML = '<img src="绿勾">';#}


           }

        }
    }







</script>
</body>
</html>