com/two/dyb作业/day1107/mypro/captchapp/urls.py
from django.urls import path

from captchapp import views

app_name = 'captchapp'

urlpatterns = [
    path('getcaptcha/',views.getcaptcha,name='getcaptcha'),
    path('index/',views.index,name='index'),
    path('check/',views.check,name='check'),
]

com/two/dyb作业/day1107/mypro/middlewareapp/urls.py
from django.urls import path

from middlewareapp import views
app_name = 'middlewareapp'


urlpatterns = [
    path('login/',views.login,name='login'),
    path('loginlogic/',views.login_logic,name='loginlogic'),
    path('welcome/',views.welcome,name='welcome'),
]

com/two/dyb作业/day1107/mypro/mypro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('captchapp/', include('captchapp.urls')),
    path('uploadapp/', include('uploadapp.urls')),
    path('middlewareapp/',include('middlewareapp.urls'))
]

com/two/dyb作业/day1107/mypro/uploadapp/urls.py
from django.urls import path

from uploadapp import views

app_name = 'uploadapp'

urlpatterns = [
    path('index/',views.index,name='index'),
    path('formlogic/',views.form_logic,name='formlogic'),
    path('query/',views.query,name='query'),

]

com/two/dyb作业/day1107/mypro/captchapp/models.py
from django.db import models

# Create your models here.

com/two/dyb作业/day1107/mypro/middlewareapp/models.py
from django.db import models

# Create your models here.

com/two/dyb作业/day1107/mypro/uploadapp/models.py
from django.db import models

# Create your models here.

# 创建model 用户上传信息 model
class User(models.Model):
    name = models.CharField(max_length=20)
    age = models.SmallIntegerField()
    birthday = models.DateTimeField()
    headpic = models.ImageField(upload_to='imgs')
    # cssfile = models.FileField(upload_to='css')
#     如果之后 接收其他上传文件 css文件  upload_to 参数

com/two/dyb作业/day1107/mypro/captchapp/views.py
import random
import string

from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.

# 视图函数 生成验证码
from captchapp.captcha.image import ImageCaptcha


def getcaptcha(request):
    # 生成验证码captcha对象
    img = ImageCaptcha()
    # 生成 码 随机码
    rst = random.sample(string.ascii_letters+string.digits,5)
    print(rst) # ['L', '9', 'd', 'o', 'Y']
    code = ''.join(rst)
    print(code) # cK2BD
    # 设置session
    request.session['code'] = code
    data = img.generate(code)
    return HttpResponse(data,'image/png')


# 验证 逻辑函数
def check(request):
    # 获取前端数据
    rst = request.POST.get('captcha')
    print(rst)
    # 后端生成数据 获取
    code = request.session.get('code')
    print(code)
    # 比对
    if rst.lower() == code.lower():
        return HttpResponse('验证成功')
    return HttpResponse('失败')


# 调用 index文件
def index(request):
    return render(request,'captchapp/index.html')


#

com/two/dyb作业/day1107/mypro/middlewareapp/views.py
from datetime import datetime

from django.http import HttpResponse
from django.shortcuts import render, redirect


# Create your views here.

# 登录
def login(request):
    print('正在登陆',datetime.now())
    return render(request,'middlewareapp/login.html')


# 登录业务逻辑
def login_logic(request):
    print('login_logic 业务逻辑处理函数',datetime.now())
    name = request.POST.get('username')
    pwd = request.POST.get('userpwd')
    if name == 'liuzong' and pwd == '123':
        # 保存登录状态
        request.session['login'] = 'ok'
        print('login_logic视图函数',datetime.now())
        return HttpResponse('登录成功')
    return HttpResponse('登录失败')

# 欢迎
def welcome(request):
    print('这是welcome视图函数',datetime.now())
    # 登录状态验证

    return render(request,'middlewareapp/welcome.html')



'''
京东
我的个人中心 我的京豆  我的订单 我的购物车 。。。。。。 登录状态验证？？？？？？
'''

com/two/dyb作业/day1107/mypro/uploadapp/views.py
import uuid

from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render
from uploadapp.models import User
import os.path
# Create your views here.

# index 视图函数
def index(request):
    return render(request,'uploadapp/index.html')

# 提交 逻辑函数

def form_logic(request):
    name = request.POST.get('username')
    age = request.POST.get('userage')
    birth = request.POST.get('userdate')
    # 针对文件 接收方式
    file = request.FILES.get('userfile')
    # uuid universally unique identifier 全球唯一标识符
    rst = str(uuid.uuid4()) + os.path.splitext(file.name)[1]
    # print(str(rst))
    # 重命名
    # 当前 文件 1.jpg字符串 splitext()
    file.name = rst
    # print(os.path.splitext(file.name))  # ('2', '.jpg')
    print(name,age,birth,file)
    # 数据 添加到数据库表
    User.objects.create(name=name,age=age,birthday=birth,headpic=file)
    return HttpResponse('接收成功')


# query 视图函数
def query(request):
    # 回传 user表数据
    number = request.GET.get('page')
    if number is None:
        number = 1
    users = User.objects.all()
    pagntor = Paginator(users,per_page=3)
    # print(pagntor.count) # 7  当前数据总条目
    # print(pagntor.num_pages) # 3  分页 总页数
    # print(pagntor.page_range) # range(1,4)  1 2 3
    print(pagntor.page(number)) #返回值：当前某页对象
    pg = pagntor.page(number)
    print(pg.object_list) # 返回值： 当前页上所有的model对象 queryset
    # # <QuerySet [<User: User object (8)>, <User: User object (9)>, <User: User object (10)>]>
    # print(pg.number) # 1 当前页码
    # print(pg.paginator) # Paginator object

    # 方法
    # print(pg.has_next()) # True
    # print(pg.has_previous()) # True
    # print(pg.has_other_pages()) # True
    # print(pg.next_page_number()) # 3
    # print(pg.previous_page_number()) # 1

    print(pg.start_index()) # 1    3条数据  4      7
    print(pg.end_index())  # 3              6      7

    return render(request,'uploadapp/query.html',{'page':pg})

com/two/dyb作业/day1107/mypro/templates/uploadapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>表单注册</title>
</head>
<body>
<form action="{% url 'uploadapp:formlogic' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    姓名： <input type="text" name="username"><br>
    年龄： <input type="text" name="userage"><br>
    生日： <input type="date" name="userdate"><br>
    头像上传： <input type="file" name="userfile"><br>
    <input type="submit" value="提交">
</form>
</body>
</html>

com/two/dyb作业/day1107/mypro/templates/uploadapp/query.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>query</title>
</head>
<body>
{% load static %}
<h1>显示所有用户信息</h1>


<table border="1">
    <tr>
        <td>编号</td>
        <td>姓名</td>
        <td>年龄</td>
        <td>生日</td>
        <td>头像</td>
    </tr>
    {% for user in page.object_list %}
        <tr>
            <td>{{ user.id }}</td>
            <td>{{ user.name }}</td>
            <td>{{ user.age }}</td>
            <td>{{ user.birthday }}</td>
            <td>
                <img src="{% static user.headpic.url %}" alt="" style="width: 100px">
            </td>
        </tr>
    {% endfor %}

</table>

{#上一页#}
{% if page.has_previous %}
    <a href="{% url 'uploadapp:query' %}?page={{ page.previous_page_number }}">上一页</a>
{% endif %}

{#{{ page.paginator.page_range }}#}
{% for foo in page.paginator.page_range %}
    <a href="{% url 'uploadapp:query' %}?page={{ foo }}">
        {% if page.number == foo %}
            <span style="background-color:red;">{{ foo }}</span>
        {% else %}
            <span>{{ foo }}</span>
        {% endif %}

    </a>
{#    如果 当前 用户 点击的 数字 要实现 样式设置 #}
{#    判断     点击数字样式设置 其他不需要#}
{% endfor %}


{#下一页#}
{% if page.has_next %}
    <a href="{% url 'uploadapp:query' %}?page={{ page.next_page_number }}">下一页</a>
{% endif %}



{#<table border="1">#}
{#    <tr>#}
{#        <td>编号</td>#}
{#        <td>姓名</td>#}
{#        <td>年龄</td>#}
{#        <td>生日</td>#}
{#        <td>头像</td>#}
{#    </tr>#}
{#    {% for user in users %}#}
{#        <tr>#}
{#            <td>{{ user.id }}</td>#}
{#            <td>{{ user.name }}</td>#}
{#            <td>{{ user.age }}</td>#}
{#            <td>{{ user.birthday }}</td>#}
{#            <td>#}
{#                <img src="{% static user.headpic.url %}" alt="" style="width: 100px">#}
{#            </td>#}
{#        </tr>#}
{#    {% endfor %}#}
{##}
{#</table>#}
</body>
</html>